import { defineConfig } from 'vite';
import { fileURLToPath } from 'node:url';

// `data/` sits outside src on purpose: it is generated by the scripts and
// committed. Aliased so imports read as `@data/segments.geojson`.
export default defineConfig({
  resolve: {
    alias: {
      '@data': fileURLToPath(new URL('./data', import.meta.url)),
    },
  },
  server: { port: 6175, strictPort: true },
});
