/**
 * Generates the pixel art: one street tileset and three character sheets.
 *
 * The art is code rather than opaque PNGs, which buys three things: it is
 * reproducible (same input, byte-identical output, so a rerun never dirties
 * the repo), it is editable (change the palette once, every tile follows), and
 * it cannot drift off-palette. Run it with:
 *
 *   corepack pnpm --filter @cloud-march/game art
 */
import sharp from 'sharp';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Canvas } from './art/canvas.mjs';
import { P } from './art/palette.mjs';
import { T, TILES } from './art/tiles.mjs';
import { CH, CW, buildCharacterSheet } from './art/character.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const assets = resolve(here, '../src/assets');

const write = async (canvas, path) => {
  mkdirSync(dirname(path), { recursive: true });
  await sharp(canvas.data, {
    raw: { width: canvas.width, height: canvas.height, channels: 4 },
  })
    // Palette PNG: correct for low-colour art and much smaller than truecolour.
    .png({ palette: true, compressionLevel: 9, effort: 10, dither: 0 })
    .toFile(path);
};

// ── Tileset ────────────────────────────────────────────────────────────────
// 8 columns keeps the sheet compact and the ids easy to reason about in Tiled.
const COLS = 8;
const rows = Math.ceil(TILES.length / COLS);
const sheet = new Canvas(COLS * T, rows * T);

TILES.forEach(([, draw], i) => {
  const tile = new Canvas(T, T);
  draw(tile);
  sheet.blit(tile, (i % COLS) * T, Math.floor(i / COLS) * T);
});

await write(sheet, join(assets, 'tilesets/street.png'));

// ── Characters ─────────────────────────────────────────────────────────────
// One rig, recoloured. Cheap variety: a crowd of visibly different people
// without a second sprite sheet to draw or maintain.
const VARIANTS = {
  citizen: {},
  citizen_teal: { shirt: '#2f8a7a', shirtShade: '#1f6357', skin: '#b87c50' },
  citizen_ochre: { shirt: '#c98a2f', shirtShade: '#9c6a1f', hair: '#3a2f28' },
};

for (const [name, palette] of Object.entries(VARIANTS)) {
  await write(buildCharacterSheet(palette), join(assets, `sprites/${name}.png`));
}

// ── Tile id manifest ───────────────────────────────────────────────────────
// Named ids so map generation and scene code never hard-code a bare number.
const ids = Object.fromEntries(TILES.map(([name], i) => [name, i]));
writeFileSync(
  join(assets, 'tilesets/street.tiles.json'),
  `${JSON.stringify(
    {
      $comment:
        'Generated by scripts/generate-art.mjs — tile name to 0-based index in street.png. Append-only: inserting a tile would renumber every map that uses it.',
      columns: COLS,
      tileSize: T,
      tileCount: TILES.length,
      ids,
    },
    null,
    2,
  )}\n`,
);

console.log(
  `✓ street.png — ${TILES.length} tiles (${COLS}x${rows} @ ${T}px = ${COLS * T}x${rows * T})`,
);
console.log(`✓ ${Object.keys(VARIANTS).length} character sheets (${CW}x${CH} frames, 4x4)`);
console.log(`✓ street.tiles.json — ${Object.keys(ids).length} named tile ids`);
